// Key sign party attestations.
//
// As in a PGP key signing party, someone you know gives you their aiwot and
// name, and you attest it by signing a statement with your key:
//
// aiwot keysignparty
// aiwot:<their aiwot>
// name:<their name>
// date:<creation time, RFC 3339>
// fake:true   (only for generated, fake attestations)
//
// The record is an `# info` section, for humans only, followed by the signed
// statement in the signed message format (`# from`, `# msg`, `# pbk`,
// `# signature`). Only the signed statement is verified. The trust in the
// attestation is the trust in its signer.

use super::{Error, Profile, DIR};
use crate::{key::SigningKey, message::SignedMessage};

/// Type of key sign party attestation records.
pub const RECORD_TYPE: &str = "keysignparty";

const STATEMENT_HEADER: &str = "aiwot keysignparty";

/// A verified key sign party attestation.
pub struct KeySign {
    /// The attested aiwot.
    pub subject: String,
    pub name: String,
    pub date: String,
    /// The aiwot of the signer.
    pub signer: String,
    /// Generated by `fakegraph`.
    pub fake: bool,
}

impl KeySign {
    pub fn profile(&self) -> Profile {
        Profile {
            platform: RECORD_TYPE,
            user: self.name.clone(),
            aiwot: self.subject.clone(),
        }
    }
}

/// Creates a signed attestation that `subject` belongs to `name`, returning
/// the record file name and content. `fake` marks generated attestations.
pub fn create(
    key: &SigningKey,
    subject: &str,
    name: &str,
    fake: bool,
) -> Result<(String, String), Error> {
    let subject = parse_aiwot(subject)?;
    check_name(name)?;
    let signer = key.aiwot();
    if subject == signer {
        return Err("you cannot attest your own aiwot".into());
    }

    let date = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
    let signed = SignedMessage::sign(key, &statement(&subject, name, &date, fake))?;

    let keysign = KeySign {
        subject,
        name: name.to_string(),
        date,
        signer,
        fake,
    };
    let record = format!(
        "# info\n\
         \n\
         - Type: {RECORD_TYPE}\n\
         - Fake: {fake}\n\
         - Created: {date}\n\
         - Profile: {profile}\n\
         - Signed by: aiwot:{signer}\n\
         \n\
         {signed}",
        date = keysign.date,
        profile = keysign.profile(),
        signer = keysign.signer,
        fake = keysign.fake,
        signed = signed.to_markdown(),
    );
    let file_name = format!(
        "{}-{RECORD_TYPE}-{}-{}.md",
        keysign.subject,
        file_name_part(name),
        &keysign.signer[..16]
    );

    Ok((file_name, record))
}

/// Creates and stores in [`DIR`] an attestation that `subject` belongs to
/// `name`, returning its path.
pub async fn attest(key: &SigningKey, subject: &str, name: &str) -> Result<String, Error> {
    let (file_name, record) = create(key, subject, name, false)?;

    // Check the record before storing it.
    verify(&record)?;

    let path = format!("{DIR}/{file_name}");
    tokio::fs::create_dir_all(DIR).await?;
    tokio::fs::write(&path, record).await?;

    Ok(path)
}

/// Verifies a key sign party record.
pub fn verify(record: &str) -> Result<KeySign, Error> {
    let (_, signed) = record
        .split_once("\n# from\n")
        .ok_or("keysignparty record has no `# from` section")?;
    let signed = SignedMessage::parse(&format!("# from\n{signed}"))?;
    signed.verify()?;

    let keysign = parse_statement(&signed.msg, signed.from.to_ascii_lowercase())?;
    if keysign.subject == keysign.signer {
        return Err("self-attestation".into());
    }

    Ok(keysign)
}

fn statement(subject: &str, name: &str, date: &str, fake: bool) -> String {
    let fake = if fake { "\nfake:true" } else { "" };
    format!("{STATEMENT_HEADER}\naiwot:{subject}\nname:{name}\ndate:{date}{fake}")
}

fn parse_statement(statement: &str, signer: String) -> Result<KeySign, Error> {
    let mut lines = statement.split('\n');
    let mut field = |prefix: &str| {
        lines
            .next()
            .and_then(|line| line.strip_prefix(prefix))
            .ok_or_else(|| format!("invalid keysignparty statement: expected `{prefix}`"))
    };

    field(STATEMENT_HEADER)?
        .is_empty()
        .then_some(())
        .ok_or("invalid keysignparty statement header")?;
    let subject = parse_aiwot(field("aiwot:")?)?;
    let name = field("name:")?.to_string();
    let date = field("date:")?.to_string();
    let fake = match lines.next() {
        None => false,
        Some("fake:true") => true,
        Some(_) => return Err("invalid keysignparty statement: unexpected content".into()),
    };
    if lines.next().is_some() {
        return Err("invalid keysignparty statement: unexpected content".into());
    }
    check_name(&name)?;

    Ok(KeySign {
        subject,
        name,
        date,
        signer,
        fake,
    })
}

/// Parses an aiwot id, with or without the `aiwot:` prefix.
fn parse_aiwot(aiwot: &str) -> Result<String, Error> {
    let aiwot = aiwot.trim();
    let aiwot = aiwot.strip_prefix("aiwot:").unwrap_or(aiwot);
    if aiwot.len() != 64 || !aiwot.bytes().all(|b| b.is_ascii_hexdigit()) {
        return Err(format!("invalid aiwot `{aiwot}`: expected 64 hex characters").into());
    }

    Ok(aiwot.to_ascii_lowercase())
}

fn check_name(name: &str) -> Result<(), Error> {
    if name.trim().is_empty() || name.trim() != name || name.chars().any(char::is_control) {
        return Err(format!("invalid name `{name}`").into());
    }

    Ok(())
}

/// Makes a name safe to use in a file name.
fn file_name_part(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-') {
                c
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::key::test_signing_key;

    #[test]
    fn test_create_verify() {
        let signer = test_signing_key();
        let subject = test_signing_key().aiwot();

        let (file_name, record) =
            create(&signer, &format!("aiwot:{subject}"), "Alice Smith", false).unwrap();
        assert_eq!(
            file_name,
            format!(
                "{subject}-keysignparty-Alice_Smith-{}.md",
                &signer.aiwot()[..16]
            )
        );
        assert!(record.starts_with("# info\n\n- Type: keysignparty\n"));

        let keysign = verify(&record).unwrap();
        assert_eq!(keysign.subject, subject);
        assert_eq!(keysign.name, "Alice Smith");
        assert_eq!(keysign.signer, signer.aiwot());
        assert_eq!(
            keysign.profile().to_string(),
            format!("keysignparty/Alice Smith/aiwot:{subject}")
        );

        // The info section is not trusted: editing it changes nothing.
        let edited = record.replace(
            "- Profile: keysignparty/Alice Smith",
            "- Profile: keysignparty/Mallory",
        );
        assert_eq!(verify(&edited).unwrap().name, "Alice Smith");

        // Editing the signed statement is detected.
        let forged = record.replace("\nname:Alice Smith\n", "\nname:Mallory\n");
        assert!(verify(&forged).is_err());
    }

    #[test]
    fn test_invalid() {
        let signer = test_signing_key();

        assert!(create(&signer, &signer.aiwot(), "me", false).is_err());
        assert!(create(&signer, "abc", "Alice", false).is_err());
        let subject = test_signing_key().aiwot();
        assert!(create(&signer, &subject, "Alice\nname:Mallory", false).is_err());
        assert!(create(&signer, &subject, " ", false).is_err());
    }
}
