// Self attestation of the public key of an aiwot.
//
// The owner of an aiwot publishes its OpenPGP public key: the MlDsa65Ed25519
// primary (whose fingerprint is the aiwot id) and its MlKem768X25519
// encryption subkey, so others can verify its signatures and signcrypt
// messages to it.
//
// # info
//
// - Type: self_attestation
// - Fake: true   (only for generated, fake identities)
// - Created: <creation time, RFC 3339>
//
// # public_key
// -----BEGIN PGP PUBLIC KEY BLOCK-----
// ...
// -----END PGP PUBLIC KEY BLOCK-----
//
// There is no separate signature: the encryption subkey's own binding
// signature, made by the primary key and checked by `verify_bindings`,
// already proves it belongs to the aiwot of the primary key.

use pgp::{
    composed::{Deserializable, SignedPublicKey},
    types::KeyDetails,
};

use super::{Error, Profile, DIR};
use crate::key::Keys;

/// Type of self attestation records.
pub const RECORD_TYPE: &str = "self_attestation";

/// A verified self attestation.
pub struct Me {
    pub aiwot: String,
    pub date: String,
    pub public: SignedPublicKey,
    /// Generated by `fakegraph`.
    pub fake: bool,
}

impl Me {
    pub fn profile(&self) -> Profile {
        Profile {
            platform: RECORD_TYPE,
            user: "self".to_string(),
            aiwot: self.aiwot.clone(),
        }
    }

    /// The fingerprint of the `MlKem768X25519` encryption subkey, if any.
    pub fn encryption_fingerprint(&self) -> Option<String> {
        self.public
            .public_subkeys
            .first()
            .map(|subkey| subkey.fingerprint().to_string())
    }
}

/// Path of the self attestation of `aiwot`.
pub fn path(aiwot: &str) -> String {
    format!("{DIR}/{aiwot}-{RECORD_TYPE}.md")
}

/// Makes sure [`DIR`] contains a valid self attestation of the current keys,
/// creating it if missing or outdated. Returns its path if it was created.
pub async fn ensure(keys: &Keys) -> Result<Option<String>, Error> {
    let aiwot = keys.aiwot();
    let path = path(&aiwot);

    match tokio::fs::read_to_string(&path).await {
        Ok(record) => match verify(&record) {
            Ok(me)
                if me.aiwot == aiwot
                    && me.encryption_fingerprint()
                        == Some(keys.encryption_subkey()?.fingerprint().to_string())
                    && !me.fake =>
            {
                return Ok(None)
            }
            Ok(_) => eprintln!("Self attestation {path} does not match the current keys"),
            Err(e) => eprintln!("Invalid self attestation {path}: {e}"),
        },
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => return Err(e.into()),
    }

    let record = create(keys, false)?;

    // Check the record before storing it.
    verify(&record)?;

    tokio::fs::create_dir_all(DIR).await?;
    tokio::fs::write(&path, record).await?;

    Ok(Some(path))
}

/// Creates a self attestation of the public key of `keys`. `fake` marks
/// generated identities.
pub fn create(keys: &Keys, fake: bool) -> Result<String, Error> {
    let aiwot = keys.aiwot();
    let date = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
    let public = keys.public().to_armored_string(Default::default())?;

    Ok(format!(
        "# info\n\
         \n\
         - Type: {RECORD_TYPE}\n\
         - Fake: {fake}\n\
         - Created: {date}\n\
         - Profile: {profile}\n\
         \n\
         # public_key\n\
         {public}",
        profile = Profile {
            platform: RECORD_TYPE,
            user: "self".to_string(),
            aiwot: aiwot.clone(),
        },
    ))
}

/// Verifies a self attestation record.
pub fn verify(record: &str) -> Result<Me, Error> {
    let fake = super::record_fake(record)?.unwrap_or(false);
    let date = super::info_field(record, "- Created:")
        .ok_or("self attestation has no `- Created:` field")?
        .to_string();

    let (_, public_key) = record
        .split_once("\n# public_key\n")
        .ok_or("self attestation has no `# public_key` section")?;
    let (public, _) = SignedPublicKey::from_string(public_key)?;
    public.verify_bindings()?;

    Ok(Me {
        aiwot: public.primary_key.fingerprint().to_string(),
        date,
        public,
        fake,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::key::test_keys;

    #[test]
    fn test_create_verify() {
        let keys = test_keys();

        let record = create(&keys, false).unwrap();
        assert!(record.starts_with("# info\n\n- Type: self_attestation\n"));

        let me = verify(&record).unwrap();
        assert_eq!(me.aiwot, keys.aiwot());
        assert_eq!(
            me.encryption_fingerprint(),
            Some(keys.encryption_subkey().unwrap().fingerprint().to_string())
        );
        assert_eq!(
            me.profile().to_string(),
            format!("self_attestation/self/aiwot:{}", keys.aiwot())
        );
        assert!(!me.fake);

        let fake = verify(&create(&keys, true).unwrap()).unwrap();
        assert!(fake.fake);

        // The aiwot of a record is whichever key it actually embeds: a
        // record with a different key is a (self-consistent) attestation of
        // that other key, not a tampered one. Rejecting a mismatch between
        // the embedded key and the claimed aiwot is `check_file_name`'s job.
        let other = test_keys();
        let other_public = other
            .public()
            .to_armored_string(Default::default())
            .unwrap();
        let ours = keys.public().to_armored_string(Default::default()).unwrap();
        let swapped = record.replace(&ours, &other_public);
        assert_eq!(verify(&swapped).unwrap().aiwot, other.aiwot());

        // Corrupting the public key breaks its bindings.
        let (info, public_key) = record.split_once("# public_key\n").unwrap();
        let corrupted = format!("{info}# public_key\n{}", public_key.replace('A', "Z"));
        assert!(verify(&corrupted).is_err());
    }
}
