// Self attestation of the public keys of an aiwot.
//
// The owner of an aiwot signs, with its hybrid signature key, a statement
// publishing its key encapsulation public key:
//
// aiwot me
// aiwot:<aiwot>
// date:<creation time, RFC 3339>
// fake:true   (only for generated, fake identities)
// kem:X25519MLKEM768
// <base58 of ml_kem_768_public || x25519_public, 100 characters per line>
//
// The signature public key is in the `# pbk` section of the signed message,
// and must be the one of `<aiwot>`. The record is an `# info` section, for
// humans only, followed by the signed statement.

use sha2::{Digest, Sha256};

use super::{Error, Profile, DIR};
use crate::{
    key::{KemKey, Keys, SigningKey},
    message::{self, SignedMessage},
};

/// Type of self attestation records.
pub const RECORD_TYPE: &str = "self_attestation";
/// Type of self attestation records written before `self_attestation`. They
/// are still accepted.
pub const LEGACY_RECORD_TYPE: &str = "me";

const STATEMENT_HEADER: &str = "aiwot me";
const KEM_ALGORITHM: &str = "X25519MLKEM768";
/// Length of an X25519MLKEM768 public key.
const KEM_PUBLIC_LEN: usize = 1184 + 32;

/// A verified self attestation.
pub struct Me {
    pub aiwot: String,
    pub date: String,
    /// X25519MLKEM768 public key: `ml_kem_768_public || x25519_public`.
    pub kem_public: Vec<u8>,
    /// Generated by `fakegraph`.
    pub fake: bool,
}

impl Me {
    pub fn profile(&self) -> Profile {
        Profile {
            platform: RECORD_TYPE,
            user: "self".to_string(),
            aiwot: self.aiwot.clone(),
        }
    }

    pub fn kem_algorithm(&self) -> &'static str {
        KEM_ALGORITHM
    }

    /// SHA-256 of the KEM public key, hex encoded.
    pub fn kem_fingerprint(&self) -> String {
        hex::encode(Sha256::digest(&self.kem_public))
    }
}

/// Path of the self attestation of `aiwot`.
pub fn path(aiwot: &str) -> String {
    format!("{DIR}/{aiwot}-{RECORD_TYPE}.md")
}

/// Path of the self attestation of `aiwot` written before `self_attestation`.
pub fn legacy_path(aiwot: &str) -> String {
    format!("{DIR}/{aiwot}-{LEGACY_RECORD_TYPE}.md")
}

/// Makes sure [`DIR`] contains a valid self attestation of the current keys,
/// creating it if missing or outdated. Returns its path if it was created.
pub async fn ensure(keys: &Keys) -> Result<Option<String>, Error> {
    let aiwot = keys.signing.aiwot();
    let path = path(&aiwot);

    match tokio::fs::read_to_string(&path).await {
        Ok(record) => match verify(&record) {
            Ok(me) if me.aiwot == aiwot && me.kem_public == keys.kem.public() && !me.fake => {
                return Ok(None)
            }
            Ok(_) => eprintln!("Self attestation {path} does not match the current keys"),
            Err(e) => eprintln!("Invalid self attestation {path}: {e}"),
        },
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => return Err(e.into()),
    }

    let record = create(&keys.signing, &keys.kem, false)?;

    // Check the record before storing it.
    verify(&record)?;

    tokio::fs::create_dir_all(DIR).await?;
    tokio::fs::write(&path, record).await?;

    Ok(Some(path))
}

/// Creates a signed self attestation of the public keys. `fake` marks
/// generated identities.
pub fn create(signing: &SigningKey, kem: &KemKey, fake: bool) -> Result<String, Error> {
    let aiwot = signing.aiwot();
    let date = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
    let kem_public = kem.public();

    let signed = SignedMessage::sign(signing, &statement(&aiwot, &date, &kem_public, fake))?;
    let me = Me {
        aiwot,
        date,
        kem_public,
        fake,
    };

    Ok(format!(
        "# info\n\
         \n\
         - Type: {RECORD_TYPE}\n\
         - Fake: {fake}\n\
         - Created: {date}\n\
         - Profile: {profile}\n\
         - KEM: {algorithm} (SHA-256 {fingerprint})\n\
         \n\
         {signed}",
        date = me.date,
        profile = me.profile(),
        algorithm = me.kem_algorithm(),
        fingerprint = me.kem_fingerprint(),
        fake = me.fake,
        signed = signed.to_markdown(),
    ))
}

/// Verifies a self attestation record.
pub fn verify(record: &str) -> Result<Me, Error> {
    let (_, signed) = record
        .split_once("\n# from\n")
        .ok_or("self attestation has no `# from` section")?;
    let signed = SignedMessage::parse(&format!("# from\n{signed}"))?;
    signed.verify()?;

    let me = parse_statement(&signed.msg)?;
    if !me.aiwot.eq_ignore_ascii_case(&signed.from) {
        return Err(format!(
            "self attestation of aiwot:{} is signed by aiwot:{}",
            me.aiwot, signed.from
        )
        .into());
    }

    Ok(me)
}

fn statement(aiwot: &str, date: &str, kem_public: &[u8], fake: bool) -> String {
    let fake = if fake { "\nfake:true" } else { "" };
    format!(
        "{STATEMENT_HEADER}\naiwot:{aiwot}\ndate:{date}{fake}\nkem:{KEM_ALGORITHM}\n{}",
        message::encode(kem_public)
    )
}

fn parse_statement(statement: &str) -> Result<Me, Error> {
    let lines: Vec<&str> = statement.split('\n').collect();
    let mut index = 0;
    let mut field = |prefix: &str| {
        let value = lines
            .get(index)
            .and_then(|line| line.strip_prefix(prefix))
            .ok_or_else(|| format!("invalid self attestation statement: expected `{prefix}`"));
        index += 1;
        value
    };

    if !field(STATEMENT_HEADER)?.is_empty() {
        return Err("invalid self attestation statement header".into());
    }
    let aiwot = field("aiwot:")?.to_ascii_lowercase();
    if aiwot.len() != 64 || !aiwot.bytes().all(|b| b.is_ascii_hexdigit()) {
        return Err(format!("invalid aiwot `{aiwot}`").into());
    }
    let date = field("date:")?.to_string();
    let fake = lines.get(3) == Some(&"fake:true");
    if fake {
        field("fake:")?;
    }
    let algorithm = field("kem:")?;
    if algorithm != KEM_ALGORITHM {
        return Err(format!("unsupported KEM algorithm `{algorithm}`").into());
    }
    let kem_start = if fake { 5 } else { 4 };
    let kem_public = message::decode("kem", &lines[kem_start.min(lines.len())..].join("\n"))?;
    if kem_public.len() != KEM_PUBLIC_LEN {
        return Err(format!(
            "KEM public key must be {KEM_PUBLIC_LEN} bytes, got {}",
            kem_public.len()
        )
        .into());
    }

    Ok(Me {
        aiwot,
        date,
        kem_public,
        fake,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::key::{test_kem_key, test_signing_key};

    #[test]
    fn test_create_verify() {
        let signing = test_signing_key();
        let kem = test_kem_key();

        let record = create(&signing, &kem, false).unwrap();
        assert!(record.starts_with("# info\n\n- Type: self_attestation\n"));
        // The base58 lines are at most 100 characters.
        assert!(record
            .lines()
            .filter(|line| !line.starts_with("- "))
            .all(|line| line.len() <= 100));

        let me = verify(&record).unwrap();
        assert_eq!(me.aiwot, signing.aiwot());
        assert_eq!(me.kem_public, kem.public());
        assert_eq!(
            me.profile().to_string(),
            format!("self_attestation/self/aiwot:{}", signing.aiwot())
        );

        assert!(!me.fake);
        let fake = verify(&create(&signing, &kem, true).unwrap()).unwrap();
        assert!(fake.fake);
        assert_eq!(fake.kem_public, kem.public());

        // Records written with the legacy type are still accepted.
        let legacy = record.replacen("- Type: self_attestation", "- Type: me", 1);
        assert!(crate::attestations::verify(&legacy, "").is_ok());

        // Replacing the KEM key is detected.
        let other = message::encode(&test_kem_key().public());
        let ours = message::encode(&kem.public());
        assert!(verify(&record.replace(&ours, &other)).is_err());
    }

    #[test]
    fn test_signed_by_other() {
        // A statement about aiwot A signed by key B is rejected.
        let a = test_signing_key();
        let b = test_signing_key();
        let kem = test_kem_key();

        let statement = statement(&a.aiwot(), "now", &kem.public(), false);
        let record = format!(
            "# info\n\n- Type: self_attestation\n\n{}",
            SignedMessage::sign(&b, &statement).unwrap().to_markdown()
        );
        assert!(verify(&record).is_err());
    }
}
