// Attestations of aiwot profiles, stored as markdown records in [`DIR`]:
//
// - `tlsnotary`: a TLSNotary notarized session with a server, whose profile is
//   extracted by the `tlsnotary::plugins` (`- Type: tlsn`).
// - `keysignparty`: another aiwot signs that it knows the owner of an aiwot (`-
//   Type: keysignparty`).
// - `me`: an aiwot signs its own public keys, including the key encapsulation
//   key (`- Type: self_attestation`, formerly `me`). Created automatically for
//   the local keys.
//
// Every record starts with an `# info` section whose `- Type:` selects how it
// is verified, and whose `- Fake:` tells whether it was generated by
// `fakegraph` (missing means `false`). A fake `tlsn` record is a statement
// signed by the identity itself (`fake`), not a TLSNotary proof. For signed
// statements the fake flag is part of the signature, and the `- Fake:` of the
// info must match it, so a fake attestation can never pass as a real one.

pub mod export;
pub mod fake;
pub mod keysignparty;
pub mod me;
pub mod tlsnotary;

use std::fmt;

use tlsnotary::plugins;

use crate::parallel::parallel_map;

pub type Error = Box<dyn std::error::Error>;

/// A profile proven by a session, displayed as
/// `<platform>/<user>/aiwot:<aiwot>`.
pub struct Profile {
    pub platform: &'static str,
    pub user: String,
    pub aiwot: String,
}

impl fmt::Display for Profile {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}/{}/aiwot:{}", self.platform, self.user, self.aiwot)
    }
}

/// Directory where attestation records are stored.
pub const DIR: &str = "db/attestations";

/// A verified attestation of an aiwot.
pub enum Attested {
    /// A TLSNotary attestation of a session with a server.
    Tlsn(tlsnotary::Verified),
    /// A key sign party attestation signed by another aiwot.
    KeySign(keysignparty::KeySign),
    /// A self attestation of the public keys of an aiwot.
    Me(me::Me),
    /// A fake TLSNotary attestation, signed by the identity itself.
    Fake(fake::Fake),
}

/// An attestation of a profile, displayed as `<platform>:<user>`, followed by
/// the signer for key sign party attestations.
pub struct ProfileAttestation {
    pub profile: Profile,
    pub signer: Option<String>,
    /// Record type and type specific details, e.g. the server or the signer.
    pub attributes: Vec<(&'static str, String)>,
    /// File name of the record.
    pub file: String,
    /// Generated by `fakegraph`.
    pub fake: bool,
}

impl std::fmt::Display for ProfileAttestation {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}:{}", self.profile.platform, self.profile.user)?;
        match &self.signer {
            Some(signer) if *signer == self.profile.aiwot => write!(f, " (self-signed)")?,
            Some(signer) => write!(f, " (signed by aiwot:{signer})")?,
            None => {}
        }
        if self.fake {
            write!(f, " [fake]")?;
        }
        Ok(())
    }
}

impl Attested {
    /// Whether the attestation was generated by `fakegraph`.
    pub fn is_fake(&self) -> bool {
        match self {
            Attested::Tlsn(_) => false,
            Attested::KeySign(keysign) => keysign.fake,
            Attested::Me(me) => me.fake,
            Attested::Fake(_) => true,
        }
    }

    /// The attested profile, from the record stored in `file`.
    pub fn attestation(self, file: String) -> Result<ProfileAttestation, Error> {
        let fake = self.is_fake();
        let mut attestation = match self {
            Attested::Tlsn(verified) => ProfileAttestation {
                profile: plugins::profile(&verified.session()).ok_or("not a known profile")??,
                signer: None,
                attributes: vec![
                    ("type", tlsnotary::RECORD_TYPE.to_string()),
                    ("server", verified.server_name.clone()),
                    (
                        "time",
                        verified
                            .time
                            .to_rfc3339_opts(chrono::SecondsFormat::Secs, true),
                    ),
                    ("notary", verified.key_hex.clone()),
                ],
                file,
                fake,
            },
            Attested::KeySign(keysign) => ProfileAttestation {
                profile: keysign.profile(),
                attributes: vec![
                    ("type", keysignparty::RECORD_TYPE.to_string()),
                    ("signer", format!("aiwot:{}", keysign.signer)),
                    ("date", keysign.date),
                ],
                signer: Some(keysign.signer),
                file,
                fake,
            },
            Attested::Me(me) => ProfileAttestation {
                profile: me.profile(),
                attributes: vec![
                    ("type", me::RECORD_TYPE.to_string()),
                    ("kem", me.kem_algorithm().to_string()),
                    ("kem_sha256", me.kem_fingerprint()),
                    ("date", me.date.clone()),
                ],
                signer: Some(me.aiwot),
                file,
                fake,
            },
            Attested::Fake(fake) => ProfileAttestation {
                profile: fake.profile(),
                signer: None,
                attributes: vec![
                    ("type", tlsnotary::RECORD_TYPE.to_string()),
                    ("server", fake.server),
                    ("date", fake.date),
                ],
                file,
                fake: true,
            },
        };
        attestation.attributes.insert(1, ("fake", fake.to_string()));

        Ok(attestation)
    }
}

/// Verifies an attestation record of any type. TLSNotary records must be
/// signed by `notary_key`.
pub fn verify(record: &str, notary_key: &str) -> Result<Attested, Error> {
    let info_fake = record_fake(record)?;

    // Records written before the type was added are TLSNotary records.
    let attested = match record_type(record).unwrap_or(tlsnotary::RECORD_TYPE) {
        tlsnotary::RECORD_TYPE if info_fake == Some(true) => Attested::Fake(fake::verify(record)?),
        tlsnotary::RECORD_TYPE => Attested::Tlsn(tlsnotary::verify(record, notary_key)?),
        keysignparty::RECORD_TYPE => Attested::KeySign(keysignparty::verify(record)?),
        me::RECORD_TYPE | me::LEGACY_RECORD_TYPE => Attested::Me(me::verify(record)?),
        other => return Err(format!("unsupported attestation type `{other}`").into()),
    };

    // Records written before the fake flag was added are not fake.
    if info_fake.unwrap_or(false) != attested.is_fake() {
        return Err("`- Fake:` of the info does not match the signed attestation".into());
    }

    Ok(attested)
}

/// Returns the `- Fake:` of an attestation record, if present.
pub fn record_fake(record: &str) -> Result<Option<bool>, Error> {
    match info_field(record, "- Fake:") {
        None => Ok(None),
        Some("true") => Ok(Some(true)),
        Some("false") => Ok(Some(false)),
        Some(other) => Err(format!("invalid `- Fake: {other}`: expected true or false").into()),
    }
}

/// Returns the `- Type:` of an attestation record, if present.
pub fn record_type(record: &str) -> Option<&str> {
    info_field(record, "- Type:")
}

/// Returns a field of the `# info` section of an attestation record.
fn info_field<'a>(record: &'a str, prefix: &str) -> Option<&'a str> {
    record
        .lines()
        .take_while(|line| !line.starts_with("## ") && !matches!(*line, "# binary" | "# from"))
        .find_map(|line| line.strip_prefix(prefix))
        .map(str::trim)
}

/// Returns the valid attestations in [`DIR`] of `aiwot`. Every candidate
/// record is fully verified; invalid ones are reported and skipped.
pub async fn attested_by(aiwot: &str, notary_key: &str) -> Result<Vec<ProfileAttestation>, Error> {
    let prefix = format!("{}-", aiwot.to_ascii_lowercase());
    Ok(valid(check(Some(&prefix), notary_key).await?))
}

/// Returns all the valid attestations in [`DIR`], sorted by aiwot and
/// profile. Invalid records are reported and skipped.
pub async fn list(notary_key: &str) -> Result<Vec<ProfileAttestation>, Error> {
    let mut attestations = valid(check(None, notary_key).await?);
    attestations.sort_by(|a, b| {
        (
            &a.profile.aiwot,
            a.profile.platform,
            &a.profile.user,
            &a.file,
        )
            .cmp(&(
                &b.profile.aiwot,
                b.profile.platform,
                &b.profile.user,
                &b.file,
            ))
    });

    Ok(attestations)
}

/// Checks every file in [`DIR`], returning the result for each one, sorted
/// by file name.
pub async fn audit(notary_key: &str) -> Result<Vec<Checked>, Error> {
    check(None, notary_key).await
}

/// The result of checking a file in [`DIR`].
pub struct Checked {
    pub file: String,
    pub result: Result<ProfileAttestation, String>,
}

/// Checks that a record file name starts with the attested aiwot, as the
/// lookup by aiwot relies on it.
fn check_file_name(file: &str, attestation: &ProfileAttestation) -> Result<(), Error> {
    let expected = format!("{}-", attestation.profile.aiwot);
    if !file.to_ascii_lowercase().starts_with(&expected) {
        return Err(format!(
            "file name does not match the attested aiwot:{}",
            attestation.profile.aiwot
        )
        .into());
    }

    Ok(())
}

/// Keeps the valid attestations, reporting the invalid ones.
fn valid(checked: Vec<Checked>) -> Vec<ProfileAttestation> {
    checked
        .into_iter()
        .filter_map(|checked| match checked.result {
            Ok(attestation) => Some(attestation),
            Err(e) => {
                eprintln!("Ignoring invalid attestation {DIR}/{}: {e}", checked.file);
                None
            }
        })
        .collect()
}

/// Verifies the files in [`DIR`] whose name starts with `prefix` (all if
/// `None`). Hidden files are ignored. A record is valid if it verifies and its
/// file name starts with the attested aiwot.
async fn check(prefix: Option<&str>, notary_key: &str) -> Result<Vec<Checked>, Error> {
    let mut entries = match tokio::fs::read_dir(DIR).await {
        Ok(entries) => entries,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => return Ok(Vec::new()),
        Err(e) => return Err(e.into()),
    };

    let mut files = Vec::new();
    while let Some(entry) = entries.next_entry().await? {
        let file = entry.file_name().to_string_lossy().into_owned();
        let name = file.to_ascii_lowercase();
        if !name.starts_with('.') && prefix.is_none_or(|prefix| name.starts_with(prefix)) {
            files.push(file);
        }
    }
    files.sort();

    let mut records = Vec::with_capacity(files.len());
    for file in files {
        let record = if file.ends_with(".md") {
            tokio::fs::read_to_string(format!("{DIR}/{file}"))
                .await
                .map_err(|e| e.to_string())
        } else {
            Err("not an attestation record: expected a `.md` file".to_string())
        };
        records.push((file, record));
    }

    // Verification is CPU bound, so records are verified in parallel.
    Ok(parallel_map(&records, |(file, record)| Checked {
        file: file.clone(),
        result: record
            .as_ref()
            .map_err(Clone::clone)
            .and_then(|record| check_record(file, record, notary_key).map_err(|e| e.to_string())),
    }))
}

/// Verifies the record stored in `file`, whose name must start with the
/// attested aiwot.
fn check_record(file: &str, record: &str, notary_key: &str) -> Result<ProfileAttestation, Error> {
    let attestation = verify(record, notary_key)?.attestation(file.to_string())?;
    check_file_name(file, &attestation)?;

    Ok(attestation)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_record_type() {
        let record = "# info\n\n- Type: tlsn\n- Created: now\n\n## Request\n\n- Type: other\n\n# binary\n\nAAAA\n";
        assert_eq!(record_type(record), Some("tlsn"));

        // Older records without a type are TLSNotary records.
        let untyped = "# info\n\n- Created: now\n\n# binary\n\nAAAA\n";
        assert_eq!(record_type(untyped), None);

        let unknown = "# info\n\n- Type: other\n\n# binary\n\nAAAA\n";
        assert_eq!(
            verify(unknown, "").err().unwrap().to_string(),
            "unsupported attestation type `other`"
        );
    }
}
