// Key sign party attestations.
//
// As in a PGP key signing party, someone you know gives you their k5 and
// name, and you attest it with a detached OpenPGP signature over a
// statement:
//
// k5 keysignparty
// k5:<their k5>
// name:<their name>
// date:<creation time, RFC 3339>
// fake:true   (only for generated, fake attestations)
//
// The record is an `# info` section, for humans only, followed by the
// `# statement` and its `# signature`, a detached OpenPGP signature. Only the
// statement and signature are verified, resolving the signer's public key
// from a [`Keyring`] by the fingerprint carried in the signature, as a real
// PGP keyring would. The trust in the attestation is the trust in its signer.

use pgp::{
    composed::{Deserializable, DetachedSignature},
    crypto::hash::HashAlgorithm,
    types::Password,
};
use rand::rngs::OsRng;

use super::{Error, Profile};
use crate::{db::Db, key::Keys, message::Keyring};

/// Type of key sign party attestation records.
pub const RECORD_TYPE: &str = "keysignparty";

const STATEMENT_HEADER: &str = "k5 keysignparty";

/// A verified key sign party attestation.
pub struct KeySign {
    /// The attested k5.
    pub subject: String,
    pub name: String,
    pub date: String,
    /// The k5 of the signer.
    pub signer: String,
    /// Generated by `fakegraph`.
    pub fake: bool,
}

impl KeySign {
    pub fn profile(&self) -> Profile {
        Profile {
            platform: RECORD_TYPE,
            user: self.name.clone(),
            k5: self.subject.clone(),
        }
    }
}

/// Creates a signed attestation that `subject` belongs to `name`, returning
/// the record file name and content. `fake` marks generated attestations.
pub fn create(
    keys: &Keys,
    subject: &str,
    name: &str,
    fake: bool,
) -> Result<(String, String), Error> {
    let subject = parse_k5(subject)?;
    check_name(name)?;
    let signer = keys.k5();
    if subject == signer {
        return Err("you cannot attest your own k5".into());
    }

    let date = chrono::Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Secs, true);
    let statement = statement(&subject, name, &date, fake);
    let signature = DetachedSignature::sign_text_data(
        OsRng,
        &keys.secret.primary_key,
        &Password::empty(),
        HashAlgorithm::Sha3_512,
        statement.as_bytes(),
    )?;
    let armored_signature = signature.to_armored_string(Default::default())?;

    let keysign = KeySign {
        subject,
        name: name.to_string(),
        date,
        signer,
        fake,
    };
    let record = format!(
        "# info\n\
         \n\
         - Type: {RECORD_TYPE}\n\
         - Fake: {fake}\n\
         - Created: {date}\n\
         - Profile: {profile}\n\
         - Signed by: k5:{signer}\n\
         \n\
         # statement\n\
         {statement}\n\
         # signature\n\
         {armored_signature}",
        date = keysign.date,
        profile = keysign.profile(),
        signer = keysign.signer,
        fake = keysign.fake,
    );
    let file_name = format!(
        "{}-{RECORD_TYPE}-{}-{}.md",
        keysign.subject,
        file_name_part(name),
        &keysign.signer[..16]
    );

    Ok((file_name, record))
}

/// Creates and stores in `db` an attestation that `subject` belongs to
/// `name`, returning where it was stored.
pub async fn attest(
    db: &dyn Db,
    keys: &Keys,
    subject: &str,
    name: &str,
    keyring: &Keyring,
) -> Result<String, Error> {
    let (file_name, record) = create(keys, subject, name, false)?;

    // Check the record before storing it.
    verify(&record, keyring)?;

    db.put(&file_name, &record).await?;

    Ok(db.location(&file_name))
}

/// Verifies a key sign party record, resolving the signer's public key from
/// `keyring` by the fingerprint carried in the signature.
pub fn verify(record: &str, keyring: &Keyring) -> Result<KeySign, Error> {
    let (_, rest) = record
        .split_once("\n# statement\n")
        .ok_or("keysignparty record has no `# statement` section")?;
    let (statement, signature) = rest
        .rsplit_once("\n# signature\n")
        .ok_or("keysignparty record has no `# signature` section")?;

    let (signature, _) = DetachedSignature::from_string(signature)?;
    let signer = signature
        .signature
        .issuer_fingerprint()
        .first()
        .ok_or("signature has no issuer fingerprint")?
        .to_string();
    let signer_key = keyring
        .get(&signer)
        .ok_or_else(|| format!("unknown signer k5:{signer}: fetch its self attestation first"))?;
    signature.verify(signer_key, statement.as_bytes())?;

    let keysign = parse_statement(statement, signer)?;
    if keysign.subject == keysign.signer {
        return Err("self-attestation".into());
    }

    Ok(keysign)
}

fn statement(subject: &str, name: &str, date: &str, fake: bool) -> String {
    let fake = if fake { "\nfake:true" } else { "" };
    format!("{STATEMENT_HEADER}\nk5:{subject}\nname:{name}\ndate:{date}{fake}")
}

fn parse_statement(statement: &str, signer: String) -> Result<KeySign, Error> {
    let mut lines = statement.split('\n');
    let mut field = |prefix: &str| {
        lines
            .next()
            .and_then(|line| line.strip_prefix(prefix))
            .ok_or_else(|| format!("invalid keysignparty statement: expected `{prefix}`"))
    };

    field(STATEMENT_HEADER)?
        .is_empty()
        .then_some(())
        .ok_or("invalid keysignparty statement header")?;
    let subject = parse_k5(field("k5:")?)?;
    let name = field("name:")?.to_string();
    let date = field("date:")?.to_string();
    let fake = match lines.next() {
        None => false,
        Some("fake:true") => true,
        Some(_) => return Err("invalid keysignparty statement: unexpected content".into()),
    };
    if lines.next().is_some() {
        return Err("invalid keysignparty statement: unexpected content".into());
    }
    check_name(&name)?;

    Ok(KeySign {
        subject,
        name,
        date,
        signer,
        fake,
    })
}

/// Parses a k5 id, with or without the `k5:` prefix.
fn parse_k5(k5: &str) -> Result<String, Error> {
    let k5 = k5.trim();
    let k5 = k5.strip_prefix("k5:").unwrap_or(k5);
    if k5.len() != 64 || !k5.bytes().all(|b| b.is_ascii_hexdigit()) {
        return Err(format!("invalid k5 `{k5}`: expected 64 hex characters").into());
    }

    Ok(k5.to_ascii_lowercase())
}

fn check_name(name: &str) -> Result<(), Error> {
    if name.trim().is_empty() || name.trim() != name || name.chars().any(char::is_control) {
        return Err(format!("invalid name `{name}`").into());
    }

    Ok(())
}

/// Makes a name safe to use in a file name.
fn file_name_part(name: &str) -> String {
    name.chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || matches!(c, '.' | '_' | '-') {
                c
            } else {
                '_'
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::key::test_keys;

    fn keyring_of(keys: &Keys) -> Keyring {
        Keyring::from([(keys.k5(), keys.public())])
    }

    #[test]
    fn test_create_verify() {
        let signer = test_keys();
        let subject = test_keys().k5();
        let keyring = keyring_of(&signer);

        let (file_name, record) =
            create(&signer, &format!("k5:{subject}"), "Alice Smith", false).unwrap();
        assert_eq!(
            file_name,
            format!(
                "{subject}-keysignparty-Alice_Smith-{}.md",
                &signer.k5()[..16]
            )
        );
        assert!(record.starts_with("# info\n\n- Type: keysignparty\n"));

        let keysign = verify(&record, &keyring).unwrap();
        assert_eq!(keysign.subject, subject);
        assert_eq!(keysign.name, "Alice Smith");
        assert_eq!(keysign.signer, signer.k5());
        assert_eq!(
            keysign.profile().to_string(),
            format!("keysignparty/Alice Smith/k5:{subject}")
        );

        // The info section is not trusted: editing it changes nothing.
        let edited = record.replace(
            "- Profile: keysignparty/Alice Smith",
            "- Profile: keysignparty/Mallory",
        );
        assert_eq!(verify(&edited, &keyring).unwrap().name, "Alice Smith");

        // Editing the signed statement is detected.
        let forged = record.replace("\nname:Alice Smith\n", "\nname:Mallory\n");
        assert!(verify(&forged, &keyring).is_err());

        // Without the signer's key in the keyring, verification fails.
        assert!(verify(&record, &Keyring::new()).is_err());
    }

    #[test]
    fn test_invalid() {
        let signer = test_keys();

        assert!(create(&signer, &signer.k5(), "me", false).is_err());
        assert!(create(&signer, "abc", "Alice", false).is_err());
        let subject = test_keys().k5();
        assert!(create(&signer, &subject, "Alice\nname:Mallory", false).is_err());
        assert!(create(&signer, &subject, " ", false).is_err());
    }
}
