// Attestations of k5 profiles, stored as markdown records in a [`Db`]:
//
// - `tlsnotary`: a TLSNotary notarized session with a server, whose profile is
//   extracted by the `tlsnotary::plugins` (`- Type: tlsn`).
// - `keysignparty`: another k5 signs that it knows the owner of a k5 (`- Type:
//   keysignparty`).
// - `iroh`: a k5 signs the iroh endpoint id it can be reached at, for
//   peer-to-peer messages and database sync (`- Type: iroh`).
// - `me`: a k5 signs its own public keys, including the key encapsulation key
//   (`- Type: self_attestation`, formerly `me`). Created automatically for the
//   local keys.
//
// Every record starts with an `# info` section whose `- Type:` selects how it
// is verified, and whose `- Fake:` tells whether it was generated by
// `fakegraph` (missing means `false`). A fake `tlsn` record is a statement
// signed by the identity itself (`fake`), not a TLSNotary proof. For signed
// statements the fake flag is part of the signature, and the `- Fake:` of the
// info must match it, so a fake attestation can never pass as a real one.

pub mod export;
pub mod fake;
pub mod iroh;
pub mod keysignparty;
pub mod me;
pub mod tlsnotary;

use std::fmt;

use anyhow::{anyhow, Context as _};
use tlsnotary::plugins;

use crate::{db::Db, k5id::K5Id, message::Keyring, parallel::parallel_map};

pub use crate::Error;

/// A profile proven by a session, displayed as
/// `<platform>/<user>/k5:<k5>`.
pub struct Profile {
    pub platform: &'static str,
    pub user: String,
    pub k5: String,
}

impl fmt::Display for Profile {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        write!(f, "{}/{}/k5:{}", self.platform, self.user, self.k5)
    }
}

/// A verified attestation of a k5.
pub enum Attested {
    /// A TLSNotary attestation of a session with a server.
    Tlsn(tlsnotary::Verified),
    /// A key sign party attestation signed by another k5.
    KeySign(keysignparty::KeySign),
    /// A self attestation of the public keys of a k5.
    Me(Box<me::Me>),
    /// A fake TLSNotary attestation, signed by the identity itself.
    Fake(fake::Fake),
    /// The iroh endpoint a k5 can be reached at, signed by the k5.
    Iroh(iroh::Iroh),
}

/// An attestation of a profile, displayed as `<platform>:<user>`, followed by
/// the signer for key sign party attestations.
pub struct ProfileAttestation {
    pub profile: Profile,
    pub signer: Option<String>,
    /// Record type and type specific details, e.g. the server or the signer.
    pub attributes: Vec<(&'static str, String)>,
    /// File name of the record.
    pub file: String,
    /// Generated by `fakegraph`.
    pub fake: bool,
}

impl std::fmt::Display for ProfileAttestation {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        write!(f, "{}:{}", self.profile.platform, self.profile.user)?;
        match &self.signer {
            Some(signer) if *signer == self.profile.k5 => write!(f, " (self-signed)")?,
            Some(signer) => write!(f, " (signed by k5:{signer})")?,
            None => {}
        }
        if self.fake {
            write!(f, " [fake]")?;
        }
        Ok(())
    }
}

impl Attested {
    /// Whether the attestation was generated by `fakegraph`.
    pub fn is_fake(&self) -> bool {
        match self {
            Attested::Tlsn(_) => false,
            Attested::KeySign(keysign) => keysign.fake,
            Attested::Me(me) => me.fake,
            Attested::Fake(_) => true,
            Attested::Iroh(_) => false,
        }
    }

    /// The attested profile, from the record stored in `file`.
    pub fn attestation(self, file: String) -> Result<ProfileAttestation, Error> {
        let fake = self.is_fake();
        let mut attestation = match self {
            Attested::Tlsn(verified) => ProfileAttestation {
                profile: plugins::profile(&verified.session()).context("not a known profile")??,
                signer: None,
                attributes: vec![
                    ("type", tlsnotary::RECORD_TYPE.to_string()),
                    ("server", verified.server_name.clone()),
                    (
                        "time",
                        verified
                            .time
                            .to_rfc3339_opts(chrono::SecondsFormat::Secs, true),
                    ),
                    ("notary", verified.key_hex.clone()),
                ],
                file,
                fake,
            },
            Attested::KeySign(keysign) => ProfileAttestation {
                profile: keysign.profile(),
                attributes: vec![
                    ("type", keysignparty::RECORD_TYPE.to_string()),
                    ("signer", format!("k5:{}", keysign.signer)),
                    ("date", keysign.date),
                ],
                signer: Some(keysign.signer),
                file,
                fake,
            },
            Attested::Me(me) => ProfileAttestation {
                profile: me.profile(),
                attributes: vec![
                    ("type", me::RECORD_TYPE.to_string()),
                    (
                        "encryption_subkey",
                        me.encryption_fingerprint().unwrap_or_default(),
                    ),
                    ("date", me.date.clone()),
                ],
                signer: Some(me.k5.clone()),
                file,
                fake,
            },
            Attested::Fake(fake) => ProfileAttestation {
                profile: fake.profile(),
                signer: None,
                attributes: vec![
                    ("type", tlsnotary::RECORD_TYPE.to_string()),
                    ("server", fake.server),
                    ("date", fake.date),
                ],
                file,
                fake: true,
            },
            Attested::Iroh(iroh) => ProfileAttestation {
                profile: iroh.profile(),
                attributes: vec![
                    ("type", iroh::RECORD_TYPE.to_string()),
                    ("endpoint", iroh.endpoint.clone()),
                    ("date", iroh.date.clone()),
                ],
                signer: Some(iroh.k5),
                file,
                fake,
            },
        };
        attestation.attributes.insert(1, ("fake", fake.to_string()));

        Ok(attestation)
    }
}

/// Verifies an attestation record of any type. TLSNotary records must be
/// signed by `notary_key`. Records signed by another k5 (key sign party
/// and fake attestations) resolve the signer's public key from `keyring`, by
/// the fingerprint carried in the signature, as a real PGP keyring would.
pub fn verify(record: &str, notary_key: &str, keyring: &Keyring) -> Result<Attested, Error> {
    let info_fake = record_fake(record)?;

    // Records written before the type was added are TLSNotary records.
    let attested = match record_type(record).unwrap_or(tlsnotary::RECORD_TYPE) {
        tlsnotary::RECORD_TYPE if info_fake == Some(true) => {
            Attested::Fake(fake::verify(record, keyring)?)
        }
        tlsnotary::RECORD_TYPE => Attested::Tlsn(tlsnotary::verify(record, notary_key)?),
        keysignparty::RECORD_TYPE => Attested::KeySign(keysignparty::verify(record, keyring)?),
        me::RECORD_TYPE => Attested::Me(Box::new(me::verify(record)?)),
        iroh::RECORD_TYPE => Attested::Iroh(iroh::verify(record, keyring)?),
        other => return Err(anyhow!("unsupported attestation type `{other}`")),
    };

    // Records written before the fake flag was added are not fake.
    if info_fake.unwrap_or(false) != attested.is_fake() {
        return Err(anyhow!(
            "`- Fake:` of the info does not match the signed attestation"
        ));
    }

    Ok(attested)
}

/// Builds a keyring of the public keys of the self attestations in `db`,
/// by k5 id, as a real PGP keyring would be built from fetched public
/// keys. Invalid records are ignored: they are reported when checked as
/// attestations in their own right.
pub async fn keyring(db: &dyn Db) -> Result<Keyring, Error> {
    let suffix = format!("-{}.md", me::RECORD_TYPE);
    let mut keyring = Keyring::new();
    let names = db.names().await?;
    for name in names {
        if !name.to_ascii_lowercase().ends_with(&suffix) {
            continue;
        }
        if let Ok(Some(record)) = db.get(&name).await {
            if let Ok(me) = me::verify(&record) {
                keyring.insert(me.k5, me.public);
            }
        }
    }

    Ok(keyring)
}

/// Returns the `- Fake:` of an attestation record, if present.
pub fn record_fake(record: &str) -> Result<Option<bool>, Error> {
    match info_field(record, "- Fake:") {
        None => Ok(None),
        Some("true") => Ok(Some(true)),
        Some("false") => Ok(Some(false)),
        Some(other) => Err(anyhow!("invalid `- Fake: {other}`: expected true or false")),
    }
}

/// Returns the `- Type:` of an attestation record, if present.
pub fn record_type(record: &str) -> Option<&str> {
    info_field(record, "- Type:")
}

/// Returns a field of the `# info` section of an attestation record.
fn info_field<'a>(record: &'a str, prefix: &str) -> Option<&'a str> {
    record
        .lines()
        .take_while(|line| !line.starts_with("## ") && !matches!(*line, "# binary" | "# from"))
        .find_map(|line| line.strip_prefix(prefix))
        .map(str::trim)
}

/// The valid attestations of a set of records, and the invalid ones that
/// were skipped.
#[derive(Default)]
pub struct Listing {
    pub attestations: Vec<ProfileAttestation>,
    pub invalid: Vec<Invalid>,
}

/// A record that failed verification.
pub struct Invalid {
    pub file: String,
    pub error: String,
}

/// Returns the valid attestations in `db` of `k5`. Every candidate
/// record is fully verified; invalid ones are returned apart.
pub async fn attested_by(db: &dyn Db, k5: &K5Id, notary_key: &str) -> Result<Listing, Error> {
    let prefix = format!("{k5}-");
    Ok(valid(check(db, Some(&prefix), notary_key).await?))
}

/// Returns the valid key sign party attestations in `db`: all the web of
/// trust is built from. Other records are not verified, which is much
/// cheaper than [`list`] (TLSNotary proofs are slow to check). Invalid key
/// sign party records are returned apart.
pub async fn keysigns(db: &dyn Db, notary_key: &str) -> Result<Listing, Error> {
    let mut records = read(db, None).await?;
    records.retain(|(_, record)| {
        record
            .as_deref()
            .is_ok_and(|record| record_type(record) == Some(keysignparty::RECORD_TYPE))
    });

    Ok(valid(verify_all(db, records, notary_key).await?))
}

/// Returns all the valid attestations in `db`, sorted by k5 and
/// profile. Invalid records are returned apart.
pub async fn list(db: &dyn Db, notary_key: &str) -> Result<Listing, Error> {
    let mut listing = valid(check(db, None, notary_key).await?);
    listing.attestations.sort_by(|a, b| {
        (&a.profile.k5, a.profile.platform, &a.profile.user, &a.file).cmp(&(
            &b.profile.k5,
            b.profile.platform,
            &b.profile.user,
            &b.file,
        ))
    });

    Ok(listing)
}

/// Checks every entry in `db`, returning the result for each one, sorted by
/// name.
pub async fn audit(db: &dyn Db, notary_key: &str) -> Result<Vec<Checked>, Error> {
    check(db, None, notary_key).await
}

/// The result of checking an entry of the database.
pub struct Checked {
    pub file: String,
    pub result: Result<ProfileAttestation, String>,
}

/// Checks that a record file name starts with the attested k5, as the
/// lookup by k5 relies on it.
fn check_file_name(file: &str, attestation: &ProfileAttestation) -> Result<(), Error> {
    let expected = format!("{}-", attestation.profile.k5);
    if !file.to_ascii_lowercase().starts_with(&expected) {
        return Err(anyhow!(
            "file name does not match the attested k5:{}",
            attestation.profile.k5
        ));
    }

    Ok(())
}

/// Splits checked records into the valid attestations and the invalid ones.
fn valid(checked: Vec<Checked>) -> Listing {
    let mut listing = Listing::default();
    for checked in checked {
        match checked.result {
            Ok(attestation) => listing.attestations.push(attestation),
            Err(error) => listing.invalid.push(Invalid {
                file: checked.file,
                error,
            }),
        }
    }

    listing
}

/// Verifies the entries in `db` whose name starts with `prefix` (all if
/// `None`). Hidden entries are ignored. A record is valid if it verifies and
/// its name starts with the attested k5.
async fn check(db: &dyn Db, prefix: Option<&str>, notary_key: &str) -> Result<Vec<Checked>, Error> {
    let records = read(db, prefix).await?;
    verify_all(db, records, notary_key).await
}

/// Reads the entries in `db` whose name starts with `prefix` (all if
/// `None`), sorted by name. Hidden entries are ignored; entries that are not
/// `.md` records are read as an error.
async fn read(
    db: &dyn Db,
    prefix: Option<&str>,
) -> Result<Vec<(String, Result<String, String>)>, Error> {
    let mut files: Vec<String> = db
        .names()
        .await?
        .into_iter()
        .filter(|file| {
            let name = file.to_ascii_lowercase();
            !name.starts_with('.') && prefix.is_none_or(|prefix| name.starts_with(prefix))
        })
        .collect();
    files.sort();

    let mut records = Vec::with_capacity(files.len());
    for file in files {
        let record = if file.ends_with(".md") {
            match db.get(&file).await {
                Ok(Some(record)) => Ok(record),
                Ok(None) => Err("the record was removed while checking".to_string()),
                Err(e) => Err(e.to_string()),
            }
        } else {
            Err("not an attestation record: expected a `.md` file".to_string())
        };
        records.push((file, record));
    }

    Ok(records)
}

/// Verifies `records`, read from `db`, against the keyring of `db`.
async fn verify_all(
    db: &dyn Db,
    records: Vec<(String, Result<String, String>)>,
    notary_key: &str,
) -> Result<Vec<Checked>, Error> {
    let keyring = keyring(db).await?;

    // Verification is CPU bound, so records are verified in parallel.
    Ok(parallel_map(&records, |(file, record)| Checked {
        file: file.clone(),
        result: record.as_ref().map_err(Clone::clone).and_then(|record| {
            check_record(file, record, notary_key, &keyring).map_err(|e| e.to_string())
        }),
    }))
}

/// Verifies the record stored in `file`, whose name must start with the
/// attested k5.
fn check_record(
    file: &str,
    record: &str,
    notary_key: &str,
    keyring: &Keyring,
) -> Result<ProfileAttestation, Error> {
    let attestation = verify(record, notary_key, keyring)?.attestation(file.to_string())?;
    check_file_name(file, &attestation)?;

    Ok(attestation)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_record_type() {
        let record = "# info\n\n- Type: tlsn\n- Created: now\n\n## Request\n\n- Type: other\n\n# binary\n\nAAAA\n";
        assert_eq!(record_type(record), Some("tlsn"));

        // Older records without a type are TLSNotary records.
        let untyped = "# info\n\n- Created: now\n\n# binary\n\nAAAA\n";
        assert_eq!(record_type(untyped), None);

        let unknown = "# info\n\n- Type: other\n\n# binary\n\nAAAA\n";
        assert_eq!(
            verify(unknown, "", &Keyring::new())
                .err()
                .unwrap()
                .to_string(),
            "unsupported attestation type `other`"
        );
    }
}
